spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:mysql://localhost:3306/employeedb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: 8476929746@lti
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    hostname: localhost

resilience4j:
  circuitbreaker:
    instances:
      EmployeeService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always




#resilience4j:
#  circuit breaker:
#    instances:
#      employee-service:
#        wait-duration-in-open-state: 1m
#        permitted-number-of-calls-in-half-open-state: 3
#        sliding-window-type: count-based
#        sliding-window-size: 5
#        minimum-number-of-calls: 5
#        slow-call-duration-threshold: 10s
#        slow-call-rate-threshold: 60
#        failure-rate-threshold: 60
        

        
